name: My First Automation

on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      story_title:
        description: 'write here title name'
        required: true
        type: string
      author_name:
        description: 'write here the name of the author'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is for ${{ inputs.customer }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ secrets.MY_FIRST_SECRET }}